import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/HeaderComponent";
import FooterComp from "@/components/FooterComp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${Geist_Mono.variable} ${Geist_Mono.variable} antialiased w-full max-w-[1152px] mx-auto bg-[#FFFFFF] dark:bg-[#FFFFFF] h-auto`}
         >
      <HeaderComponent />
      {children}
      <FooterComp />
    </body>  
        
        
      </html >
    );
}


